### PR TITLE
NEW GUI

### PR DESCRIPTION
**Pull request by zeroainz**
I think i fixed all known bugs with this fork 
For now no support for pvp mp(not used to determinate player's force for storing things).
No support of dynamic price and tax.
Added the ability to set manualy resource/item price for bfk-mods(big-fkng-mods) with a lot of raw resource and new fluids
Delete of Chinese language.
Modified some variable names.
Modified all buy/sell logic, from original mod there is only the pricing system
xD if there is somthing wrong add me on discord : ZeroAinz, i'm from italy and my free time to work on it is in the late evening/early night with local time.
!!!Sorry for bad github usage :)
385901365-f7488be2-014c-4676-b044-196a5990ba51

### CODE REVIEW

**Comment by zeroainz** [comment]
Before approving, many changes need to be made to optimize compatibility with the missing functions.

**Comment by djmango** [comment]
Hmm these changes are significant - I was looking to just merge a new GUI with search and other nice-to-haves. The majority of your changes are fine as a fork but I don't think makes sense to update the main mod with all of them. What do you guys think @lmst2 @LoganDark ?

**Comment by LoganDark** [comment]
it looks like this changes the name and ID of the mod, changes the author, erases all the changelogs and a bunch of the README, removes a bunch of features and settings (the dynamic pricing system can actually be quite important for balance), and also isn't compatible with my most recent quality updates (not compatible with modded qualities, uses the index of the item in the dropdown instead of the level of the quality)... I think this is borderline unmergeable as-is, I think the effort is appreciated and the GUI does look a bit better (always hated it being in the top left corner, always behind the inventory window so I always have to move the inventory window which is so annoying...) but IMHO there are too many other compromises made to make it here.

**Comment by djmango** [comment]
Yeah appreciate the work making this a PR @zeroainz, I was just thinking this is a GUI update. If it's possible to improve the gui within the current version of the mod that would be great, but otherwise I don't believe we can accomodate

**Comment by lmst2** [comment]
Hi, sorry for the late reply, just saw the message tonight. [LoganDark](https://github.com/LoganDark) says it all lol. I agree with him. This seems more like a fork than a PR. Besides the change of author and change log, the icon is different. So I guess this is a modified version of this mod? I see it changes a lot of things. only the basic file structure remains. The control.lua (where main logic lives) is more like a rewrite version with few similarities to what we have here. So i think this is not suitable for merging. Besides that, the GUI is really good. So instead of merging entire codebase. If you can make a fork of our current one and add the GUI as a new "functionality" and then make a PR, that would be great.

**Comment by LoganDark** [comment]
> If you can make a fork of our current one and add the GUI as a new "functionality" and then make a PR, that would be great.

I wouldn't merge it until it supports everything our current GUI does (I care enough about modded qualities being supported), but once it does I agree it'd be an improvement.

**Comment by lmst2** [comment]
agree, needs a little tweak on that.

**Pull request closed without merging**
