### PR TITLE
add basic support for factorio 2.0 and space age dlc

### PR DESCRIPTION
**Pull request by lmst2**
Hi, 

Can't wait to play space age with black market, so I just do it my self.
few issues still have here:
- besides the sales price changed when sale high quality items, the sold item price show on the gui is still the original price (the u coin in your wallet increase correctly). I guess that is related to how gui access the price. it might just get the price by item name in global storage. but to fix this needs a big change in how price is stored. need to add a dictionary of prices according to quality.
what I did is just change the sell_trader function, play with the numbers. there are works to do, and I just want to get it to work as soon as possible.
- another issue is we can't buy the high quality items. this is also related to price (either store different prices or play with the numbers) and some gui jobs, I personally don't know factorio gui very well, so I didn't do it. leave it for others lol. And I think this is a pretty good balance, since if you can just buy any high quality items, then the game turns way too easily.

Anyway, enjoy black market in space age:)
hope this pr can be merged.
best wishes

### CODE REVIEW

**Comment by djmango** [comment]
Thanks for this! Looks great, merging

**Comment by lmst2** [comment]
> Thanks for this! Looks great, merging

thanks for merging, one thing I forgot to mention. the image of the trader tank is expanded by 2x. I don't know what hapoend but when i load the mod, its keep showing 'The given sprite rectangle is outside the actual sprite size' and i see it is trying to cut the rectangle with double the height of the picture. I tried set 'scale=0.5' to that picture but it didn't work. so i have to expande the actual picture lol. don't know what happened, is there other parts that controlz the picture size? I can't find it. looked into styles.lua but haven't see something simillar. leave it to you haha.

**Comment by djmango** [comment]
do you mean we should use the old size or the expanded size? I saw that file changed

**Comment by lmst2** [comment]
> do you mean we should use the old size or the expanded size? I saw that file changed
don't know, just mention that, its better if all the pics are identical sized, but, if you can't find the problem, then just leave it that way is okey, as long as it is working lol.

**Comment by djmango** [comment]
Does it give you a warning rn?

**Comment by lmst2** [comment]
> Does it give you a warning rn?

no warnings, perfectly fine, just curious what caused this

**Comment by djmango** [comment]
Sorry it's been a while since I've worked on the codebase. Have you tried using an LLM repo query tool? Tons out there rn

**Pull request merged**
