### PR TITLE
Fix modded qualities

### LINKED ISSUE #55: Crash when selling item with quality above Legendary
https://mods.factorio.com/mod/BlackMarket2/discussion/672825e69a7e098a2efc61f3

When a mod adds any quality levels above legendary, you can't sell anything with those quality levels because it throws an unrecoverable error

You also can't buy anything with those quality levels either

### PR DESCRIPTION
**Pull request by LoganDark**
1. get all quality prototypes and build a sorted list of them
2. display the list in the quality dropdown
3. since there can be gaps in level, translate dropdown indices to real quality levels and back
4. for compatibility with existing saves, quality level 0 is represented as index 1, and so on
5. for vanilla quality levels, the existing multipliers are kept, but all modded quality levels will use an exponential function to calculate their multiplier

image

Fixes #55

### CODE REVIEW

**Comment by djmango** [comment]
Looks great! Thanks

**Comment by LoganDark** [comment]
> based on you code we can know that the level of legendary is 6 instead of 5

Screenshot 2024-11-04 124337

Oh I didn't know that legendary in vanilla was level 5. I thought it was level 4.

I'll open another PR to fix this and also #60

**Comment by lmst2** [comment]
> > based on you code we can know that the level of legendary is 6 instead of 5
> 
> Screenshot 2024-11-04 124337
> 
> Oh I didn't know that legendary in vanilla was level 5. I thought it was level 4.
> 
> I'll open another PR to fix this and also #60

oh yeah, after reading your code, when add items to drop down menu, the index should start with 1, this also confused me when i testing

**Comment by LoganDark** [comment]
#61

**Comment by LoganDark** [comment]
> it looks like the quality level are not continuous. so either you can make your own list with continuous index to make the price calculate smoother

yes, this list is already `quality_list`

> but if you have a mod makes a quality level 100, you get 35 * 3^100 on the price lol.

intended :)

**Pull request merged**
